import { prisma } from './prisma'
import { writeFile, mkdir } from 'fs/promises'
import { exec } from 'child_process'
import { promisify } from 'util'
import path from 'path'
import { existsSync } from 'fs'

const execAsync = promisify(exec)

export async function syncNASShares() {
  try {
    // Get all enabled shares from database
    const shares = await prisma.nasShare.findMany({
      where: { enabled: true },
    })

    // Sync NFS exports
    await syncNFSExports(shares)

    // Sync SMB shares
    await syncSMBShares(shares)

    return {
      success: true,
      nfsCount: shares.filter(s => s.protocol === 'NFS').length,
      smbCount: shares.filter(s => s.protocol === 'SMB').length,
    }
  } catch (error: any) {
    console.error('Error syncing NAS shares:', error)
    throw error
  }
}

async function syncNFSExports(shares: any[]) {
  const nfsShares = shares.filter(s => s.protocol === 'NFS')
  
  if (nfsShares.length === 0) {
    return
  }

  // Generate exports file
  let exportsContent = '# NFS Exports - Auto-generated by UniFi Drive NAS\n'
  exportsContent += '# DO NOT EDIT MANUALLY - Changes will be overwritten\n\n'

  for (const share of nfsShares) {
    const options = share.permissions === 'READ_WRITE' 
      ? 'rw,sync,no_subtree_check,no_root_squash'
      : 'ro,sync,no_subtree_check,no_root_squash'
    
    const allowedIPs = share.allowedIPs 
      ? `(${share.allowedIPs.split(',').map((ip: string) => ip.trim()).join(',')})`
      : '*'
    
    exportsContent += `${share.path} ${allowedIPs}(${options})\n`
  }

  // Write to exports file in shared volume
  // The /shared/nfs volume is mounted in both app and nfs-server containers
  const exportsDir = '/shared/nfs'
  const exportsPath = `${exportsDir}/shares.exports`
  
  try {
    // Ensure directory exists
    if (!existsSync(exportsDir)) {
      await mkdir(exportsDir, { recursive: true })
    }
    
    await writeFile(exportsPath, exportsContent, 'utf8')
    console.log(`NFS exports written to ${exportsPath}`)
    
    // The watch script in the NFS container will pick this up automatically
    // But we can also try to trigger a reload immediately
    try {
      await execAsync('docker exec nas_nfs_server exportfs -ra 2>/dev/null || true')
      console.log('NFS exports reloaded successfully')
    } catch (error) {
      console.warn('Could not automatically reload NFS exports. The watch script will reload it shortly.')
    }
  } catch (error: any) {
    console.error('Error writing NFS exports:', error)
    // Fallback: log configuration for manual setup
    console.log('NFS Exports configuration (fallback):')
    console.log(exportsContent)
  }
}

async function syncSMBShares(shares: any[]) {
  const smbShares = shares.filter(s => s.protocol === 'SMB')
  
  if (smbShares.length === 0) {
    return
  }

  let smbConfig = `[global]
   workgroup = WORKGROUP
   server string = UniFi Drive NAS
   security = user
   map to guest = Bad User
   dns proxy = no

`

  for (const share of smbShares) {
    const readOnly = share.permissions === 'READ_ONLY' ? 'yes' : 'no'
    
    smbConfig += `[${share.name}]
   path = ${share.path}
   browseable = yes
   writable = ${share.permissions === 'READ_WRITE' ? 'yes' : 'no'}
   read only = ${readOnly}
   guest ok = yes
   create mask = 0664
   directory mask = 0775
   valid users = guest
   public = yes

`
  }

  // Write to smb config file in shared volume
  // The /shared/smb volume is mounted in both app and samba containers
  const smbDir = '/shared/smb'
  const smbConfigPath = `${smbDir}/shares.conf`
  
  try {
    // Ensure directory exists
    if (!existsSync(smbDir)) {
      await mkdir(smbDir, { recursive: true })
    }
    
    await writeFile(smbConfigPath, smbConfig, 'utf8')
    console.log(`SMB config written to ${smbConfigPath}`)
    
    // The watch script in the Samba container will pick this up automatically
    // But we can also try to trigger a reload immediately
    try {
      await execAsync('docker exec nas_samba_server smbcontrol all reload-config 2>/dev/null || true')
      console.log('Samba config reloaded successfully')
    } catch (error) {
      console.warn('Could not automatically reload Samba config. The watch script will reload it shortly.')
    }
  } catch (error: any) {
    console.error('Error writing SMB config:', error)
    // Fallback: log configuration for manual setup
    console.log('SMB Configuration (fallback):')
    console.log(smbConfig)
  }
}

